### ISSUE TITLE
The time is not clear or obvious

### ISSUE THREAD

**Issue by flurbius** [ashutoshgngwr/10-bitClockWidget#96]
The following is entirely from guessing as there is very little information to go on

You have an arrangement of 4 dots on the left to represent the hour(?) and 6 on the right for the minutes(?)
However in one screenshot there were 12 dots all together.

The dots appear to be binary with the most significant half placed on top of the least significant half.

Is this right?
If so why such a complicated display

**Comment by ashutoshgngwr** [comment]
> You have an arrangement of 4 dots on the left to represent the hour(?) and 6 on the right for the minutes(?)

Yup. There's a separator that you can enable from the settings. The first two/three (depending on 12/24 hour configuration) columns are hours. The last three columns are minutes. The bottom right corner is the least, and the top left is the most significant bit.

> If so why such a complicated display

It started as a 10-bit clock. Arraning hours and minutes in rows would result in 6 columns rather than 5. At the time, it seemed like a good idea. I'm closing this because changing the time representation now will adversely affect existing users.
